In [2]:
import os
import polars as pl


FILE_PATH = "../data/raw/apbd_indonesia_2011_2026.parquet"  

file_size_bytes = os.path.getsize(FILE_PATH)
file_size_mb = file_size_bytes / (1024 * 1024)

df_lazy = pl.scan_parquet(FILE_PATH)
total_rows = df_lazy.select(pl.len()).collect().item()

print("=== HASIL VERIFIKASI DATASET ===")
print(f"Ukuran File  : {file_size_mb:.2f} MB")
print(f"Jumlah Baris : {total_rows:,} baris\n")

is_size_ok = file_size_mb >= 500
is_rows_ok = total_rows > 1_000_000

if is_size_ok or is_rows_ok:
    print(" STATUS: MEMENUHI KRITERIA TUGAS!")
    if is_rows_ok:
        print(
            f"   - Kriteria Baris Terpenuhi: {total_rows:,} > 1.000.000 baris."
        )
    if is_size_ok:
        print(f"   - Kriteria Ukuran Terpenuhi: {file_size_mb:.2f} MB >= 500 MB.")
else:
    print(" STATUS: TIDAK MEMENUHI KRITERIA (Kurang dari 500MB DAN < 1 Juta baris).")

=== HASIL VERIFIKASI DATASET ===
Ukuran File  : 13.58 MB
Jumlah Baris : 3,132,863 baris

 STATUS: MEMENUHI KRITERIA TUGAS!
   - Kriteria Baris Terpenuhi: 3,132,863 > 1.000.000 baris.

In [4]:
display(df_lazy.head(5).collect())

print(df_lazy.collect_schema())

df_lazy.select([
    pl.col("anggaran").mean().alias("mean_anggaran"),
    pl.col("realisasi").mean().alias("mean_realisasi"),
]).collect()

shape: (5, 11)
┌───────┬───────┬─────────────┬──────────┬───┬────────────────┬───────────┬───────────┬────────────┐
│ tahun ┆ bulan ┆ id_provinsi ┆ provinsi ┆ … ┆ akun           ┆ anggaran  ┆ realisasi ┆ persentase │
│ ---   ┆ ---   ┆ ---         ┆ ---      ┆   ┆ ---            ┆ ---       ┆ ---       ┆ ---        │
│ i16   ┆ i8    ┆ str         ┆ str      ┆   ┆ str            ┆ f64       ┆ f64       ┆ f64        │
╞═══════╪═══════╪═════════════╪══════════╪═══╪════════════════╪═══════════╪═══════════╪════════════╡
│ 2011  ┆ 1     ┆ 01          ┆ Provinsi ┆ … ┆ Pendapatan     ┆ 7.0894e12 ┆ 7.6093e12 ┆ 107.33     │
│       ┆       ┆             ┆ Aceh     ┆   ┆                ┆           ┆           ┆            │
│ 2011  ┆ 1     ┆ 01          ┆ Provinsi ┆ … ┆ PAD            ┆ 7.9728e11 ┆ 8.0284e11 ┆ 100.7      │
│       ┆       ┆             ┆ Aceh     ┆   ┆                ┆           ┆           ┆            │
│ 2011  ┆ 1     ┆ 01          ┆ Provinsi ┆ … ┆ Pajak Daerah   ┆ 6.2271e11 ┆ 5.8618e11 ┆ 94.13      │
│       ┆       ┆             ┆ Aceh     ┆   ┆                ┆           ┆           ┆            │
│ 2011  ┆ 1     ┆ 01          ┆ Provinsi ┆ … ┆ Retribusi      ┆ 1.3264e10 ┆ 9.4160e9  ┆ 70.99      │
│       ┆       ┆             ┆ Aceh     ┆   ┆ Daerah         ┆           ┆           ┆            │
│ 2011  ┆ 1     ┆ 01          ┆ Provinsi ┆ … ┆ Hasil          ┆ 1.0200e11 ┆ 6.6007e10 ┆ 64.71      │
│       ┆       ┆             ┆ Aceh     ┆   ┆ Pengelolaan    ┆           ┆           ┆            │
│       ┆       ┆             ┆          ┆   ┆ Kekayaan Dae…  ┆           ┆           ┆            │
└───────┴───────┴─────────────┴──────────┴───┴────────────────┴───────────┴───────────┴────────────┘

Schema({'tahun': Int16, 'bulan': Int8, 'id_provinsi': String, 'provinsi': String, 'id_pemda': String, 'pemda': String, 'no_akun': Int16, 'akun': String, 'anggaran': Float64, 'realisasi': Float64, 'persentase': Float64})

shape: (1, 2)
┌───────────────┬────────────────┐
│ mean_anggaran ┆ mean_realisasi │
│ ---           ┆ ---            │
│ f64           ┆ f64            │
╞═══════════════╪════════════════╡
│ 3.8731e11     ┆ 3.1824e11      │
└───────────────┴────────────────┘